
export const PictureTypes: any = {
    OPEN_CLUSTER: 'Amas ouvert',
    GLOBULAR_CLUSTER: 'Amas globulaire',
    NEBULAR_STAR_CLUSTER: "Amas d'étoiles + Nébuleuse",
    GALAXY: 'Galaxy',
    GALAXY_PAIR: 'Pair galaxy',
    GALAXY_TRIPLET: 'Triplet galaxy',
    PLANETARY_NEBULAR: 'Nébuleuse Planétaire',
    HII_IONIZED_REGION: 'Nébuleuse HII',
    DARK_NEBULAR: 'Nébuleuse obscure',
    EMISSION_NEBULA: 'Nébuleuse émission',
    NEBULAR: 'Nébuleuse',
    REFLECTION_NEBULA: 'Nébuleuse réflection',
    SUPERNOVA_REMNANT: 'Supernova rémanente',
    NOVA_STAR: 'Etoile Nova',
    COMETE: 'Comète',
    SATELLITE: 'Satellite',
    PLANET: 'Planète',
}